'use client';

import { useState, useRef } from 'react';
import Link from 'next/link';
import { Navigation } from '@/components/shared/Navigation';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import type { InsightsPayload, AIResponse } from '@/lib/types';

const TIME_RANGES = [
  { value: '7d', label: 'Last 7 days' },
  { value: '30d', label: 'Last 30 days' },
  { value: '90d', label: 'Last 90 days' },
];

interface WeeklyBrief {
  insights: InsightsPayload;
  aiSummary: AIResponse | null;
  generatedAt: Date;
}

export default function ReportsPage() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [report, setReport] = useState<WeeklyBrief | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [timeRange, setTimeRange] = useState('30d');
  const [copySuccess, setCopySuccess] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  const handleGenerateReport = async () => {
    setIsGenerating(true);
    setError(null);

    try {
      // Fetch insights data
      const insightsResponse = await fetch(`/api/insights?time_range=${timeRange}`);
      const insights: InsightsPayload = await insightsResponse.json();

      if (!insightsResponse.ok) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        throw new Error((insights as any).error || 'Failed to fetch insights');
      }

      // Generate AI summary
      const askResponse = await fetch('/api/ask', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          question: `Generate a comprehensive weekly brief for my shop. Summarize key performance, highlight wins and concerns, and give me 3 actionable recommendations for the coming week.`,
          time_range: timeRange,
        }),
      });

      let aiSummary: AIResponse | null = null;
      if (askResponse.ok) {
        aiSummary = await askResponse.json();
      }

      setReport({
        insights,
        aiSummary,
        generatedAt: new Date(),
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate report');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopySummary = async () => {
    if (!report?.aiSummary) return;

    const summary = `
Weekly Brief - ${report.generatedAt.toLocaleDateString()}

SUMMARY
${report.aiSummary.summary}

KEY METRICS
- Revenue: $${report.insights.kpis.revenue.toLocaleString()}
- Orders: ${report.insights.kpis.orders}
- Average Order Value: $${report.insights.kpis.aov.toFixed(2)}
- Returning Customers: ${report.insights.kpis.returning_pct.toFixed(1)}%

${report.aiSummary.risks.length > 0 ? `RISKS\n${report.aiSummary.risks.map(r => `- ${r}`).join('\n')}` : ''}

${report.aiSummary.opportunities.length > 0 ? `OPPORTUNITIES\n${report.aiSummary.opportunities.map(o => `- ${o}`).join('\n')}` : ''}

RECOMMENDED ACTIONS
${report.aiSummary.actions.map((a, i) => `${i + 1}. ${a}`).join('\n')}

Generated by SellerScope
    `.trim();

    try {
      await navigator.clipboard.writeText(summary);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleExportPDF = () => {
    window.print();
  };

  const formatCurrency = (value: number) =>
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value);

  return (
    <div className="min-h-screen bg-gray-50">
      <Navigation />

      <main className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8">
        <div className="mb-8 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Weekly Brief</h1>
            <p className="mt-2 text-sm text-gray-600">
              Generate and export performance reports
            </p>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-sm text-gray-600">Time range:</span>
            <select
              value={timeRange}
              onChange={(e) => setTimeRange(e.target.value)}
              className="rounded-md border border-gray-300 bg-white text-gray-900 px-3 py-1.5 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
              disabled={isGenerating}
            >
              {TIME_RANGES.map((range) => (
                <option key={range.value} value={range.value}>
                  {range.label}
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* Generate Report Card */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Generate Report</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-sm text-gray-600">
              Create a comprehensive weekly brief with KPIs, top products, trends, and AI-powered actionable insights.
            </p>
            <div className="flex flex-wrap gap-3">
              <Button onClick={handleGenerateReport} disabled={isGenerating}>
                {isGenerating ? (
                  <>
                    <svg className="animate-spin -ml-1 mr-2 h-4 w-4" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                    </svg>
                    Generating...
                  </>
                ) : (
                  'Generate Weekly Brief'
                )}
              </Button>
              {report && (
                <>
                  <Button variant="outline" onClick={handleExportPDF}>
                    Export as PDF
                  </Button>
                  <Button variant="outline" onClick={handleCopySummary}>
                    {copySuccess ? 'Copied!' : 'Copy Summary'}
                  </Button>
                </>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Error State */}
        {error && (
          <div className="rounded-lg border border-red-200 bg-red-50 p-4 mb-6">
            <div className="flex">
              <svg className="h-5 w-5 text-red-400" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
              </svg>
              <div className="ml-3">
                <p className="text-sm text-red-700">{error}</p>
                <p className="mt-1 text-sm text-red-600">
                  Make sure you&apos;ve seeded the database from the{' '}
                  <Link href="/settings" className="underline">Settings page</Link>.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Report Content */}
        {report && (
          <div ref={reportRef} className="space-y-6 print:space-y-4">
            {/* Report Header */}
            <Card className="print:shadow-none print:border-0">
              <CardContent className="pt-6">
                <div className="text-center border-b pb-4 mb-4">
                  <h2 className="text-2xl font-bold text-gray-900">Weekly Performance Brief</h2>
                  <p className="text-sm text-gray-500 mt-1">
                    {TIME_RANGES.find(r => r.value === timeRange)?.label} ending {report.generatedAt.toLocaleDateString()}
                  </p>
                </div>

                {/* KPI Grid */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                  <div className="text-center p-4 bg-gray-50 rounded-lg">
                    <p className="text-2xl font-bold text-gray-900">{formatCurrency(report.insights.kpis.revenue)}</p>
                    <p className="text-xs text-gray-500 mt-1">Revenue</p>
                    <Badge variant={report.insights.trends.revenue_change_pct >= 0 ? 'default' : 'danger'} className="mt-2">
                      {report.insights.trends.revenue_change_pct >= 0 ? '+' : ''}{report.insights.trends.revenue_change_pct.toFixed(1)}%
                    </Badge>
                  </div>
                  <div className="text-center p-4 bg-gray-50 rounded-lg">
                    <p className="text-2xl font-bold text-gray-900">{report.insights.kpis.orders}</p>
                    <p className="text-xs text-gray-500 mt-1">Orders</p>
                    <Badge variant={report.insights.trends.orders_change_pct >= 0 ? 'default' : 'danger'} className="mt-2">
                      {report.insights.trends.orders_change_pct >= 0 ? '+' : ''}{report.insights.trends.orders_change_pct.toFixed(1)}%
                    </Badge>
                  </div>
                  <div className="text-center p-4 bg-gray-50 rounded-lg">
                    <p className="text-2xl font-bold text-gray-900">{formatCurrency(report.insights.kpis.aov)}</p>
                    <p className="text-xs text-gray-500 mt-1">Avg Order Value</p>
                    <Badge variant={report.insights.trends.aov_change_pct >= 0 ? 'default' : 'danger'} className="mt-2">
                      {report.insights.trends.aov_change_pct >= 0 ? '+' : ''}{report.insights.trends.aov_change_pct.toFixed(1)}%
                    </Badge>
                  </div>
                  <div className="text-center p-4 bg-gray-50 rounded-lg">
                    <p className="text-2xl font-bold text-gray-900">{report.insights.kpis.returning_pct.toFixed(1)}%</p>
                    <p className="text-xs text-gray-500 mt-1">Returning Customers</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* AI Summary */}
            {report.aiSummary && (
              <Card className="print:shadow-none print:border-0">
                <CardHeader>
                  <CardTitle className="text-lg">Executive Summary</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <p className="text-gray-700">{report.aiSummary.summary}</p>

                  {report.aiSummary.risks.length > 0 && (
                    <div>
                      <h4 className="font-semibold text-red-700 mb-2">Risks & Concerns</h4>
                      <ul className="list-disc list-inside space-y-1">
                        {report.aiSummary.risks.map((risk, i) => (
                          <li key={i} className="text-sm text-gray-700">{risk}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {report.aiSummary.opportunities.length > 0 && (
                    <div>
                      <h4 className="font-semibold text-green-700 mb-2">Opportunities</h4>
                      <ul className="list-disc list-inside space-y-1">
                        {report.aiSummary.opportunities.map((opp, i) => (
                          <li key={i} className="text-sm text-gray-700">{opp}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  <div>
                    <h4 className="font-semibold text-blue-700 mb-2">Recommended Actions</h4>
                    <ol className="list-decimal list-inside space-y-1">
                      {report.aiSummary.actions.map((action, i) => (
                        <li key={i} className="text-sm text-gray-700">{action}</li>
                      ))}
                    </ol>
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Top Products */}
            <Card className="print:shadow-none print:border-0">
              <CardHeader>
                <CardTitle className="text-lg">Top Products</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="overflow-x-auto">
                  <table className="min-w-full divide-y divide-gray-200">
                    <thead>
                      <tr>
                        <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">Product</th>
                        <th className="px-3 py-2 text-right text-xs font-medium text-gray-500 uppercase">Units</th>
                        <th className="px-3 py-2 text-right text-xs font-medium text-gray-500 uppercase">Revenue</th>
                        <th className="px-3 py-2 text-right text-xs font-medium text-gray-500 uppercase">Trend</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                      {report.insights.top_products.slice(0, 10).map((product, idx) => (
                        <tr key={idx}>
                          <td className="px-3 py-2">
                            <div className="text-sm font-medium text-gray-900">{product.name}</div>
                            <div className="text-xs text-gray-500">{product.category}</div>
                          </td>
                          <td className="px-3 py-2 text-right text-sm text-gray-700">{product.units}</td>
                          <td className="px-3 py-2 text-right text-sm text-gray-700">{formatCurrency(product.revenue)}</td>
                          <td className="px-3 py-2 text-right">
                            <span className={product.trend_pct >= 0 ? 'text-green-600' : 'text-red-600'}>
                              {product.trend_pct >= 0 ? '+' : ''}{product.trend_pct.toFixed(1)}%
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>

            {/* Category Breakdown */}
            <Card className="print:shadow-none print:border-0">
              <CardHeader>
                <CardTitle className="text-lg">Category Breakdown</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {report.insights.category_breakdown.map((category, idx) => (
                    <div key={idx} className="flex items-center gap-3">
                      <div className="flex-1">
                        <div className="flex justify-between text-sm mb-1">
                          <span className="font-medium text-gray-900">{category.category}</span>
                          <span className="text-gray-600">{formatCurrency(category.revenue)} ({category.pct_of_total}%)</span>
                        </div>
                        <div className="w-full bg-gray-200 rounded-full h-2">
                          <div
                            className="bg-blue-600 h-2 rounded-full"
                            style={{ width: `${category.pct_of_total}%` }}
                          />
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Footer CTA */}
            <Card className="bg-gradient-to-r from-blue-50 to-indigo-50 border-blue-200 print:hidden">
              <CardContent className="py-4">
                <div className="flex items-center justify-between">
                  <p className="text-sm text-gray-700">
                    Want to dig deeper into these insights?
                  </p>
                  <Link href={`/ask?topic=report&range=${timeRange}`}>
                    <Button variant="outline" size="sm">
                      Ask your Shop
                      <svg className="ml-1 w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                      </svg>
                    </Button>
                  </Link>
                </div>
              </CardContent>
            </Card>
          </div>
        )}
      </main>
    </div>
  );
}
